### ISSUE TITLE
Website is down "Service unavailable"

### ISSUE THREAD

**Issue by Merith-TK** [SkyrimTogether/issues-website#29]
## Description
website is down
https://i.imgur.com/CwQnp2X.png

## Service
- [X] Website
- [ ] Authentication/Login service
- [ ] API

## Your environment
* OS: Windows 10 
* Browser: Firefox

## Reproduction rate
100%

## Steps to reproduce
IDK

## Actual result
https://i.imgur.com/CwQnp2X.png

## Expected result
site to actually load

## Evidence (optional)
https://i.imgur.com/CwQnp2X.png

## Final checks for the reporter
https://i.imgur.com/CwQnp2X.png
- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/61426105-090bac00-a8ce-11e9-929f-bf547b89f219.png)

**Comment by ajsmith21** [comment]
Wow, no response to this huh? 12 days and nothing!

**Comment by Dumbeldor** [comment]
Hi,

Thank your for reporting the problem to us ! But we already know that.
The website is closed until a new web developer is recruited. But yeah it is true that normally we will have to have the background with our icon, but it's not a priority problem.

We keep you informed of the progress of the website development on discord, for the moment i close this issue. @Merith-TK thank you for taking the time to make this issue happen. @ajsmith21  we have a lot of open issues to deal with.

Have fun !
