### ISSUE TITLE
Pictures are broken on certain news page

### ISSUE THREAD

**Issue by Dragonisser** [SkyrimTogether/issues-website#4]
## Description
^title

## Service
- [x] Website
- [ ] Authentication/Login service
- [ ] API

## Your environment
* OS: Windows 10
* Browser: Chrome

## Reproduction rate
- Everytime

## Steps to reproduce
Just click on the website on the specific news titled "community-spotlight" and you will see the issue

## Actual result
Cant see 2 of the images

## Expected result
Can see every image

**Comment by f13rce** [comment]
Fixed it, thank you for the report.

Note to self: Use the correct folder to upload images, else only admins see it :)

**Comment by Dragonisser** [comment]
Works now again.
