### ISSUE TITLE
Password Reset 

### ISSUE THREAD

**Issue by CaptainThiccRich** [SkyrimTogether/issues-website#6]
## Description
A short description about your issue or detailed description for a feature request.

## Service
- [X] Website
- [X] Authentication/Login service

## Your environment
* OS:  Windows 10 Pro 
* Browser: Microsoft Edge 

## Reproduction rate
How many times can you reproduce it? Every Time Until the option completely vanished ((hopefully you guys caught it)) 

edit: repeatable every time following the link in 'steps to reproduce' 

## Steps to reproduce
Tell us how to reproduce this issue.

follow steps for #8 and then follow password reset prompt 

then proceed to type in email address, and submit it. Get a tasty error message talking about Username Conditions not being met, and no email is sent. 

## Actual result
No email received, and a rather spicy error message, as pictured below 

## Expected result
expected email address to be accepted, and to receive a code to reset password

## Evidence (optional)

![passwordreseterror](https://user-images.githubusercontent.com/45950351/50999845-3a707d00-1523-11e9-8831-e2a106f7b1ed.JPG)

**Comment by Skorm92** [comment]
Password reset is not available during the closed beta as no SMTP server will be connected during this period.
